### ISSUE TITLE
Cura 4.2.1 upgrade process

### ISSUE THREAD

**Issue by EvilSpock** [trouch/CreawsomeMod#100]
Is there or  what is the process to go from Creawesome 4.1 to Cura 4.2.1 with no errors. Do we do a restore to remove Creawesome before upgrading to Cura 4.2.1 or just run the upgrade to 4.2.1.
It would be helpful to know and maybe update the front page with an update.
Thanks

**Comment by trouch** [comment]
README updated.

**Comment by EvilSpock** [comment]
updated readme does not answer the question which should be simple to answer.

**Comment by trouch** [comment]
sorry, there isn't any particular instruction.
just backup settings then update as it should be without thinking about the mod.
