### ISSUE TITLE
Ender 3 model missing in Cura

### ISSUE THREAD

**Issue by namadori** [trouch/CreawsomeMod#106]
I really liked the full Ender 3 model in the preview, I understand it was too big to be included for everyone. 
What about republishing the files with a quick guide on how to install them?

**Comment by jonnypage** [comment]
I second this, I'd love to have the model in again

**Comment by natshi25** [comment]
can i third this?

**Comment by adrianmihalko** [comment]
Anyone?

**Comment by nallath** [comment]
If someone puts in the effort to reduce the mesh so that it's not too big, it can be added again.

**Comment by trouch** [comment]
duplicate of #112
