### ISSUE TITLE
Profile cannot be opened with Ender 3 printer selected in Cura 4.2.1

### ISSUE THREAD

**Issue by MisterPrintf** [trouch/CreawsomeMod#109]
If you attempt to open the included profile (which was created for and on a custom Ender 3 machine profile) while having the Creawesome mod's Ender 3 profile selected, you will recieve the following error:
The machine defined in profile C:/Users/Brandt/Documents/Thingiverse Profile.curaprofile (fdmprinter) doesn't match with your current machine (creality_base), could not import it.

I'm not entirely sure what's going on here. Perhaps you could shed some light onto this?
[Broken Profile.zip](https://github.com/trouch/CreawsomeMod/files/3608232/Broken.Profile.zip)

**Comment by nallath** [comment]
This is fixed for Cura 4.3
