### ISSUE TITLE
Cura 4.3, Ender 3 line width is back to 0.4mm

### ISSUE THREAD

**Issue by juckendesAuge** [trouch/CreawsomeMod#111]
Hello,

the line width of Cura 4.3 for the Creality Ender 3 is set to 0.4 again.
Is this a mistake of Cura or Ultimaker?
What was the line width for Cura version 4.2 with Ender 3?

Thank you

**Comment by trouch** [comment]
Please check changes in Ultimaker/Cura changelog. 
Unfortunately few people disagreed and reverted back to 0.4 at some point.
