### ISSUE TITLE
Support generation

### ISSUE THREAD

**Issue by frozenPG** [trouch/CreawsomeMod#113]
This mode elevates the quality to a great level. Unfortunately, it messes up the support generation :( Since it was hard coded into Cura 4.2 and newer, it is quite a problem. Even messes with support interface. See the screens.
![cura-problem2](https://user-images.githubusercontent.com/57573791/68534625-be0f1c00-0336-11ea-95e7-b503515a9b8c.jpg)
![cura-problem](https://user-images.githubusercontent.com/57573791/68534637-d3844600-0336-11ea-9a9f-413f3b18aea1.jpg)
![supp](https://user-images.githubusercontent.com/57573791/68534652-ff073080-0336-11ea-9f5d-3ce56eca7bc8.jpg)

**Comment by frozenPG** [comment]
it should look like this (from working 4.1):
![correct](https://user-images.githubusercontent.com/57573791/68534677-6fae4d00-0337-11ea-80e7-723035e99d0d.JPG)

**Comment by pearlsails** [comment]
Oh, this is a nightmare, the 4.3 version is so bad compared to the older one for 4.1. Walls have issues fusing together, support generation is awful. I've replaced the hotend and calibrated esteps and still issues. Wish we still had the option to get the old one as i cant get it back now

**Comment by frozenPG** [comment]
OK, I made some progress. It seems, that from reasons unknown Crewasome mod (hardcoded in Cura >4.2), changed DEFAULT settings for supports! So if you come with your previously flowless support settings from previous versions, it will simply fail. Your profile contains only changes (what is not changed is taken from default Cura settings WHICH HAS CHANGED!). Even the standard profiles in Cura will fail at creating reasonable supports! So, what is the solution? Simple. Open your working profile in Cura 4.1, show ALL settings, make notes (screens) from the support section and then compare it with Cura 4.3 - change accordingly. Done :)
