### ISSUE TITLE
How i install creawmod on Windows cura 4 

### ISSUE THREAD

**Issue by Lui2004** [trouch/CreawsomeMod#115]
Hi

I dont know how to install creawmod on cura4 in Windows 10?

Thanks

**Comment by dezmaeth** [comment]
Have the same issue, cant figure it out

**Comment by obbista** [comment]
Ottimo sito

**Comment by nallath** [comment]
The most recent version of Cura (4.4) has it pre-installed. So no need to install any of this by hand.

**Comment by fabianoasevedo** [comment]
if it is pre-installed, how do you install it?

**Comment by trouch** [comment]
Just install latest Cura and you will get most of this the improvement in the bundled default Creality machine configurations.
