### ISSUE TITLE
Nouveau logo

### ISSUE THREAD

**Issue by Guilouz** [trouch/CreawsomeMod#12]
Salut,
je t'ai fait un boot logo un peu plus classe avec transparence si ça t'intéresse.

![cura](https://user-images.githubusercontent.com/12702322/58279518-e6ae5400-7d9e-11e9-874c-685a2b7a23d5.png)

**Comment by eptak** [comment]
Merci !

**Comment by trouch** [comment]
ajouté à la beta 3, c'est bien mieux !
merci :-)

**Comment by Guilouz** [comment]
Nouvelle version en corrigeant la faute. Je t'ajouerais que je n'avais pas fait gaffe non plus.

J'ai bien sûr laissé la faute dans le nom du mod.

![cura](https://user-images.githubusercontent.com/12702322/58587998-f62a1300-825e-11e9-8b9a-c081ad7955e4.png)
