### ISSUE TITLE
No Ender 5 support

### ISSUE THREAD

**Issue by Vessehune** [trouch/CreawsomeMod#14]
Ender 5 is not on the list.  I will try ender 3 settings, but would love to see Ender 5 on printer list.

**Comment by pjratl** [comment]
A an Ender 5 owner I too would like to see this

**Comment by rap66** [comment]
Also an Ender5 owner, please add this printer.

**Comment by reloxx13** [comment]
same board, same stepper, same extruder. use ender 3 and change the bed size. done

**Comment by trouch** [comment]
ender 5 on the corner with beta 3, but you can use ender-3 and adjust machine height as suggested here

**Comment by emhcth** [comment]
Is it possible to remove the machine preview until the 5 is there? How would the "upgrade" work once the Ender 5 is implemented?  BTW nice work.

**Comment by trouch** [comment]
added to beta 3
