### ISSUE TITLE
Install profiles without overwriting Cura install files

### ISSUE THREAD

**Issue by mroote** [trouch/CreawsomeMod#16]
Hello,

Is there a way to install just the printing profile without the other modifications to Cura?

Thanks

**Comment by LucaKaufmann** [comment]
+1, would be nice if it was possible to just add the "Creawsome" printer as a new printer but be able to keep the existing one with all the profiles

**Comment by trouch** [comment]
Fixed for new installs with Beta 3
Please cleanup cache and user settings eventually
https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations
