### ISSUE TITLE
How can i choose a 0.3mm nozzle?

### ISSUE THREAD

**Issue by lospo** [trouch/CreawsomeMod#19]
As object, how can i configure a 0.3mm nozzle?
I can see only 
0.2
0.4
0.6
0.8

**Comment by reloxx13** [comment]
layer height is not nozzle diameter.

**Comment by conicio** [comment]
I have the same problem. I got 0.3, 0.4, 0.5 and 0.7 nozzles and can't select them. Why only even numbers?

**Comment by trouch** [comment]
This is per choice as I started with the CR-10S Pro that only has those one.
Will add 0.3 and 0.5 with beta 3.

**Comment by lospo** [comment]
Thank for the great job, Trouch, I will wait for your beta 3 :D

**Comment by trouch** [comment]
added to beta 3
