### ISSUE TITLE
Slicing problem

### ISSUE THREAD

**Issue by melou61** [trouch/CreawsomeMod#21]
Hello, I have a problem when slicing with your mod. As you can see in the pictures attached, in the prepare mode is all good, but when you change to the preview mode I cannot see the small details. Can you tell me how to solve this issue? Thanks
![WechatIMG128](https://user-images.githubusercontent.com/37929000/58369780-b29e7480-7eff-11e9-93a6-e656ed246f37.jpeg)
![WechatIMG129](https://user-images.githubusercontent.com/37929000/58369781-b29e7480-7eff-11e9-8f13-09d08ff998a6.jpeg)

**Comment by kaskii** [comment]
Try to enable "Print Thin Walls".

**Comment by louis-lau** [comment]
Just FYI, if the above setting works it just means the details are smaller than your nozzle diameter/line width. Nothing to do with this mod.

**Comment by melou61** [comment]
It works for now, thanks.
