### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by melou61** [trouch/CreawsomeMod#22]
As seen in the attached picture, I cannot get access to the marketplace plugins.

![WechatIMG130](https://user-images.githubusercontent.com/37929000/58370353-c8af3380-7f05-11e9-942a-4339b79348fb.jpeg)

**Comment by MrKaos98** [comment]
That should be internet connection related problem I think since it works fine for me. All plugins are visible..

**Comment by melou61** [comment]
My internet connexion is fine. I closed and reopen Cura a few times and still the same, I've even reinstalled and nothing, still the same. I'm using MacOS Mojave 10.14.3

**Comment by b1naryVap0r** [comment]
uninstall the cura 4, and reinstall. does can you access the market place without doing the creawesome mod? if yes, then close cura and  move the resources folder from the creawesome mod back into the cura directory, reopen and see if the behavior still exists?  it works for me on windows 10.

**Comment by eptak** [comment]
Marketplace working fine !

**Comment by melou61** [comment]
Thanks, it is working now.
