### ISSUE TITLE
Where does the source code live?

### ISSUE THREAD

**Issue by probonopd** [trouch/CreawsomeMod#32]
Thanks for starting this project, it's great to see a community effort to produce top-notch profiles for Creality printers.

> First of all, download the CreawsomeMod package then follow instructions according to your operating system. DO NOT DOWNLOAD THE ZIP FILE FROM THE CLONE BUTTON.

Where do the files inside the zip come from, shouldn't they be in the GitHub repository so that one can see who changed/added/removed what, and so that one can contribute?

Also, I would imagine that by far not all of those files in the zip have actually been changed. Which ones have?

Is this code be supposed to be a mod (almost forked application) in the long run, or should the Creality profiles be contributed back to the original Cura project eventually?

**Comment by trouch** [comment]
added source code used into this repo with beta 3
I don't plan to push it upstream only couple reason
- keep control of releases
- being able to make mods that won't be accepted upstream such as the Creawsome machine category
