### ISSUE TITLE
Skirt is not the first thing to print

### ISSUE THREAD

**Issue by ToddMangan** [trouch/CreawsomeMod#34]
When I start my print the skirt is not the first item to be printed

**Comment by trouch** [comment]
seems a bug in Cura 4... removed skirt when support are enabled with beta 3 of the mod

**Comment by Firedrops** [comment]
that doesn't sound like an ideal solution... is there a way to print bed adhesion before supports?

**Comment by trouch** [comment]
Haven't found that !

**Comment by jrfoell** [comment]
I'm seeing the same issue, a small part of the print is being laid down before the skirt.

**Comment by Gaz83** [comment]
Not sure if it helps but I am printing brim and brim always prints before model.

**Comment by tvixen** [comment]
I have no problems skirt. It's set to 4 pr. default, and it work out of the box.
Did also try with brim....works too.

**Comment by trouch** [comment]
I believe it has been fixed in Cura since then.
