### ISSUE TITLE
Nozzle Size says "Empty"

### ISSUE THREAD

**Issue by astrolasher** [trouch/CreawsomeMod#35]
When I click on the nozzle tab in the Cura 4.0 modded software, under the Nozzle size tab it says empty and no matter how many times I click, it won't allow me to choose a nozzle size. Has anyone else encountered this problem? If so, please give me a solution. I would be very grateful.

**Comment by trouch** [comment]
Fixed for new installs with Beta 3
Please cleanup cache and user settings eventually
https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations
