### ISSUE TITLE
Ender 3 Nozzle pulls threads outside the model at regular intervals

### ISSUE THREAD

**Issue by felixscherze** [trouch/CreawsomeMod#42]
#bug  I have an Ender 3. When I print an object, the nozzle passes over the object at regular intervals, extruding filament. can someone help me further

**Comment by cbygh** [comment]
I don't know if this is what you mean, but I had something like that. It's the first print I did with this mod.
The nozzle went outside the print and then continued normally.
![creawbug](https://user-images.githubusercontent.com/33999996/58745697-76fe3000-8454-11e9-994c-aeafd9df5c43.jpg)

**Comment by tvixen** [comment]
Try this:
Travel
Combine Mode: All
Max Comb Distance With No Retract: 5

**Comment by trouch** [comment]
Enable Z hop.
