### ISSUE TITLE
Slicing never start

### ISSUE THREAD

**Issue by xTremePower** [trouch/CreawsomeMod#43]
Hi,

I really want to try your mod, I installed them on Cura 4.1.0 but since when I clic on Slice, the progress bar never go up....

I reinstalled Cura 4.1.0 (without erasing settings, and without the mod it's work again

**Comment by drock1985** [comment]
You may need to downgrade to Cura 4.0

**Comment by trouch** [comment]
Not supported yet, duplicate #18
