### ISSUE TITLE
can we have a profile optimized for speed?

### ISSUE THREAD

**Issue by pjratl** [trouch/CreawsomeMod#44]
especially nice for when protyping....

**Comment by pjratl** [comment]
My attempt at this profile prints at ~2x speed only tested on simple box shapes at the moment

**Comment by nallath** [comment]
Cura doesn't have a system for this (yet). It is something that we want to work on, so I'd recommend waiting for those changes before starting on that.

**Comment by tvixen** [comment]
I have added a profile where my Ender 3 Pro is running 250mm/s and stored it under profiles. 
So it's not a problem to make a speed profile. (the extruder has a little trouble following, but thats ok, as it's  only for very quick jobs. Prototypes aso.)
