### ISSUE TITLE
Package Size

### ISSUE THREAD

**Issue by stelgenhof** [trouch/CreawsomeMod#48]
The Beta-3 package contains a lot of files that are a copy of the original Cura installation resources folder (for example, firmware hex files). Is it necessary to include all of these files in this package?

Wouldn't it be sufficient only to package those files that are covered by this mod?

Cheers! Sacha

**Comment by trouch** [comment]
this is done for convenience for easy removal and avoid issue with merging folders.

**Comment by nallath** [comment]
This is actually what causes the mod to break on every update of Cura.
