### ISSUE TITLE
cura 4.1

### ISSUE THREAD

**Issue by Georgetheold** [trouch/CreawsomeMod#49]
it says "cura can't start"

**Comment by dfptown** [comment]
I am having same/similar problem. Cura 4.1 says configuration problem. I did notice that the resources file from here has 14 items and the old one in the cura package has 15. The missing one is "texts".
But the detailed crash log says problem with a qml file.

**Comment by ptyork** [comment]
It's not supported yet. See #18.

**Comment by trouch** [comment]
Uploaded package for Cura 4.1
