### ISSUE TITLE
klipper support

### ISSUE THREAD

**Issue by fiveNinePlusR** [trouch/CreawsomeMod#50]
does this work with modified firmware like klipper? 

https://github.com/KevinOConnor/klipper

**Comment by ptyork** [comment]
Yep. Cura 4.0 + OctoPi + Klipper + Gen L + CR-10s works great...

**Comment by trouch** [comment]
it's firmware and mostly machine agnostic

**Comment by fiveNinePlusR** [comment]
cool thanks!
