### ISSUE TITLE
Cura start gcode settings changes not being kept.

### ISSUE THREAD

**Issue by yfaykya** [trouch/CreawsomeMod#54]
Hi,
I add a G29 to start gcode but anytime I look at the generated gcode it is not there.

**Comment by trouch** [comment]
cannot reproduce it !

**Comment by b1naryVap0r** [comment]
I have g29 on my install for bltouch and works without issue after multiple prints.

Maybe there was something you had to do to cura initially to configure auto bed leveling and it was removed during the mod install?

Try to uninstall and then reinstall cura with no mod to confirm it functions then install the mod to confirm you still have the problem.

**Comment by yfaykya** [comment]
Only thing I did was edit the start gcode in printer settings. I will have
another dig at it today to see what I may have missed.

**Comment by yfaykya** [comment]
Working now. I might have had multiple curas open or something. Closing. (and thanks!)
