### ISSUE TITLE
Cura 4.1 crashes and wont open when launching with CreawsomeMod installed

### ISSUE THREAD

**Issue by SimplySomething** [trouch/CreawsomeMod#57]
I put the resources folder in the cura file after having removed the old file, and now whenever i try to launch cura it crashes. if i remove the resources folder provided by the Creawsome Mod, and replace the original file it runs vanilla cura with no problems.

![Cura wont start](https://user-images.githubusercontent.com/51178541/58594460-4db28980-8233-11e9-837b-b785104090ec.png)
![Cura](https://user-images.githubusercontent.com/51178541/58594461-4db28980-8233-11e9-8440-9b9fc2cd2096.png)
![Crash report](https://user-images.githubusercontent.com/51178541/58594462-4db28980-8233-11e9-9242-782db64f7007.png)

**Comment by trouch** [comment]
I've added some warning to the main page and uploaded a new package for Cura 4.1.
I highly recommend to reset your Cura settings and revert back to your old resources. Then you can proceed with Cura update and mod reinstall using the new package.
