### ISSUE TITLE
Pillowing

### ISSUE THREAD

**Issue by rlogiacco** [trouch/CreawsomeMod#58]
There must be something wrong in how I altered the included profiles, but I'm experiencing a lot of pillowing: 3 top layers, 2 walls, your settings for cooling (100% at layer 4), 0.5mm wall line, 20% infill (pattern changed to cubic subdivision), zig-zag top-bottom pattern...

I wasn't having any pillowing before the switch to your mod, but it might depend on something I changed so I'm not really opening an issue, just asking for an informed opinion.
![photo_2019-05-30_00-23-13](https://user-images.githubusercontent.com/199473/58595510-31354200-8271-11e9-9071-2bcbc257a3ff.jpg)

**Comment by trouch** [comment]
definitely your settings that aren't matching. not a mod issue as you say. try with standard default setting first.
