### ISSUE TITLE
Lines support has connect lines as default

### ISSUE THREAD

**Issue by kort0175** [trouch/CreawsomeMod#59]
Before Creawesome I was using lines support so that I could see the model being printed and they were easier to remove. Now they are connected by a shell and very hard to remove. Connect lines is not checked, but is also hidden when lines is chosen. Any ideas?

**Comment by kort0175** [comment]
My problem was Support Line Wall Count. Hope this helps.

**Comment by Al3601** [comment]
i have the same problem, on all profiles , my support stuck on my models , impossibl to remove, what solution have you found ?

**Comment by 1aTa** [comment]
Set 'Support Wall Line Count' to 0.

**Comment by kort0175** [comment]
I am using the settings from this video.

https://youtu.be/QaE7YPvh4E8

**Comment by kort0175** [comment]
I am using the settings from this video.

https://youtu.be/QaE7YPvh4E8
