### ISSUE TITLE
Default bed size of CR10s is 310x310?

### ISSUE THREAD

**Issue by alastaira** [trouch/CreawsomeMod#6]
Hi! Thanks very much for sharing your work on this.
I'm still tuning settings but noticed one thing that puzzled me - the profile for a CR10s specifies the bed width and height of 310mm (in resources\definitions\creality_cr10.def.json). Shouldn't this be 300mm x 300mm?

**Comment by chunter1** [comment]
Should be 300 x 300 to not collide with the clamps

**Comment by trouch** [comment]
fixed in upcoming beta 3
