### ISSUE TITLE
Gaps at start of each print line

### ISSUE THREAD

**Issue by gerhick** [trouch/CreawsomeMod#61]
Hi all, I upgraded to creawesome yesterday and it looks great, but I'm getting a problem where the start of each line has a slight delay, maybe 1 or 2mm and its consistent - see attached images. 

I thought it was related to retraction but I've disabled retraction and its still happening - albeit less so...

Note in the images attached the part orientation is the same, the break happens top right in each case...

Any suggestions?

![20190530_210142](https://user-images.githubusercontent.com/20733682/58629044-a9a60c80-831e-11e9-922e-f681acb56788.jpg)
![20190530_210207](https://user-images.githubusercontent.com/20733682/58629046-a9a60c80-831e-11e9-8bee-cceaa60bb187.jpg)

**Comment by malikobaid** [comment]
Having the same issue after update

**Comment by trouch** [comment]
this is typical to bed adhesion or levelling issue.
