### ISSUE TITLE
4.1 CreawsomeMod does not open (Mac)

### ISSUE THREAD

**Issue by ren9216** [trouch/CreawsomeMod#63]
Hi! I am having the same issue as SimplySomething. After loading it takes me to the reset nad backup configuration, and it wont open. I tried reseting cura already updated and then reinstalled the mod, but does not work.
I am new at this so detailed explanation on how to do it would be amazing!
Thanks!

**Comment by ToneStrife** [comment]
Same to me. Cura 4.1

**Comment by BarbaRufa** [comment]
Exact same here.  Downloaded a fresh 4.1 copy from Ultimaker's web site. Downloaded the 4.1 mod and unfortunately cannot open.

**Comment by ToneStrife** [comment]
Found the answer. Instructions are wrong. The folder to copy is resources, inside of resources.
Cura.app/Contents/Resources/Resources

**Comment by BarbaRufa** [comment]
ToneStrife. you are a genius. Thanks.

**Comment by trouch** [comment]
Doc is as clear as possible with a screenshot and arrows. 
![macos](https://github.com/trouch/CreawsomeMod/raw/master/doc/img/macos.png)

Look ... Contents.... Resources (capital R) then ressource (lower R)...
