### ISSUE TITLE
prints are 0.2 layer height no mater what profile i  select

### ISSUE THREAD

**Issue by davelandrygmail** [trouch/CreawsomeMod#64]
no matter what profile i select my layer heights are always 0.2

using cura 4.1 and cr-10 mini

**Comment by davelandrygmail** [comment]
Performed some more investigations with a fresh install on a new PC.

The issue is Dynamic Quality.  Every other profile has Layer Height = Initial Layer Height except for Dynamic where Layer Height = 0.16 and Initial Layer Height = 2.0 

So this might be a bug with Cura.

**Comment by trouch** [comment]
Could you provide an STL to replicate the issue ?

**Comment by davelandrygmail** [comment]
good morning please see attached files

![image](https://user-images.githubusercontent.com/51218913/58955234-6bb74700-8769-11e9-8a80-581be7ec2e5f.png)


[CCR10_CHEPCalibrationCube.gcode.txt](https://github.com/trouch/CreawsomeMod/files/3257114/CCR10_CHEPCalibrationCube.gcode.txt)

**Comment by trouch** [comment]
this model is mostly vertical, but stills show some layer height change on the preview.
Please use another STL with more slopes to see more changes.
<img width="1552" alt="MacBookPro 2019-06-06 at 23 49 46" src="https://user-images.githubusercontent.com/2722443/59068894-d5dd0280-88b5-11e9-8722-4688e3ea69f8.png">
