### ISSUE TITLE
Increase overhang angle supports on ender 3

### ISSUE THREAD

**Issue by BenNottelling** [trouch/CreawsomeMod#67]
I'm talking about this setting
![image](https://user-images.githubusercontent.com/17304943/58751879-f80bf600-8459-11e9-8f41-928700a49809.png)

I did a angle test print with this profile and got some really nice results (from 30 - 85 degree angles)
So I propose the default setting on this be increased to maybe 60 or 70 degrees
![IMG_20190601_104003](https://user-images.githubusercontent.com/17304943/58751914-8e401c00-845a-11e9-910f-f29610bca0a4.jpg)

![IMG_20190601_104955](https://user-images.githubusercontent.com/17304943/58751942-1aeada00-845b-11e9-9a0e-2dd393b42f15.jpg)

I printed with hatchbox PLA at 200c on the hot end and 50c on the bed. Oh, and 0.2 mm layer height

**Comment by trouch** [comment]
please give more info 
- layer fan type - stock or modded
- layer fan duct - stock or modded
- fan speed
- print orientation

**Comment by BenNottelling** [comment]
My bad
Fan type is and duct are both stock
Speed I believe is the default for this profile
Print orientation is the same as it's seen in the pictures (otherwise this test would be pretty useless) 
Can I run another print to double check the print speed if you want

**Comment by trouch** [comment]
Thanks, but there are two pictures with different orientation on the Z axis. was it aligned with Y axis ?

**Comment by BenNottelling** [comment]
Ohhhh that's what you meant, yeah I'll have to start the print again so I can see what direction it's printing

**Comment by trouch** [comment]
airflow direction has big impact on the overhang !

**Comment by BenNottelling** [comment]
Here I did a reprint with it facing both directions, I only printed from 50-85 degrees so it would save time, but I kept the same settings as last time, does that help?
![IMG_20190602_121857](https://user-images.githubusercontent.com/17304943/58766257-36c0af80-8531-11e9-8503-51ebfcad92d5.jpg)
![IMG_20190602_121921](https://user-images.githubusercontent.com/17304943/58766261-3b856380-8531-11e9-8eb3-6cd4abfbc969.jpg)
![IMG_20190602_121927](https://user-images.githubusercontent.com/17304943/58766262-3cb69080-8531-11e9-9afd-5be1f12ae366.jpg)

**Comment by trouch** [comment]
honestly, increasing to 75° doesn't sound a good idea unless super efficient cooling.
