### ISSUE TITLE
Custom material profile not working with Cura 4.1 - Release b3.2

### ISSUE THREAD

**Issue by kintarojs** [trouch/CreawsomeMod#68]
Optimized profiles are not available when custom material profile is used.
Material profile is a duplication of generic PLA one.

Fresh install of Cura 4.1 & mod b3.2.
Ender 3

![Capture](https://user-images.githubusercontent.com/16974550/58759431-0de8ec00-852a-11e9-9714-7ff670441e0d.PNG)

**Comment by trouch** [comment]
you need to change `Material Type` from **PLA+** to **PLA** (remove the `+`)
