### ISSUE TITLE
Top layer not sliced when using latest mod with Cura 4.1.0

### ISSUE THREAD

**Issue by DennisHeijmans** [trouch/CreawsomeMod#70]
When slicing with default Ender-3 top layer is sliced.

**Comment by trouch** [comment]
not enough information.... please provide settings used and eventually the model.

**Comment by DennisHeijmans** [comment]
Eventually found i had spiral vase mode on by default. Also 5.0 nozzle width is no good.

Met vriendelijke groet,

Dennis Heijmans
