### ISSUE TITLE
Supports Difficult to Remove

### ISSUE THREAD

**Issue by agrias** [trouch/CreawsomeMod#73]
Using Cura 4.0 and printing with supports even with 5% support density is super hard without breaking the print. Any advice/guidance would be appreciated

**Comment by trouch** [comment]
What version of the mod and what quality / layer height are used ?

**Comment by agrias** [comment]
CreawsomeMod-0.2.zip , Standard / .2

Will try with Creawsome3

**Comment by trouch** [comment]
interface has been fixed with beta 3. please report if it still happening.

**Comment by agrias** [comment]
@trouch Even with beta 3 the supports are still extremely difficult to remove. I did a new installation of 3.0 and had no better luck

**Comment by Al3601** [comment]
@agrias i solved this problem by applying this settings (tested for PLA & PETG) (creawsome Beta3.2 + cura 4.1.0)
![support](https://user-images.githubusercontent.com/33935485/59286519-2e265280-8c70-11e9-912c-60ac323a2287.JPG)

hope this can help you, by the way is was the only problem i was facing with Creawsome

**Comment by RFC1795** [comment]
I'm having the same problem. Even with those suggested settings @Al3601 ... a bit better, but I couldn't get the support off, even using a long nose pliers :(
