### ISSUE TITLE
Gaps at start of each print line - Try again

### ISSUE THREAD

**Issue by gerhick** [trouch/CreawsomeMod#77]
re-posting this issue: https://github.com/trouch/CreawsomeMod/issues/61

**trouch** commented 13 hours ago
this is typical to bed adhesion or levelling issue.

What the hell?!
That's such a frustrating and dismissive comment.

Bed level is done via BLTouch, and bed adhesion is via ABS Juice - both work perfectly.
Neither problem even has symptoms like this.

As an update, I reverted back to the original printer configuration in Cura and the problem has immediately cleared up. So obviously the problem is with the configuration.

**Comment by trouch** [comment]
> Bed level is done via BLTouch, and bed adhesion is via ABS Juice - both work perfectly.
> Neither problem even has symptoms like this.

How should I guess that ? You are not even mentioning material and settings used.

With regard to your thing touch:
1. BLTouch itself doesn't _level_ your bed which is a physical adjustment.
2. ABL only _compensate_ unleveled and warped bed.

Having said that, you may need to replace the M420 from the start gcode by a G29 to force probing right before the print, easy to try.

Then, you may have a slight leak between the PTFE and nozzle. In that case, you'll have partial clogging upon retract which could also explain gaps on restart. Such leak can't be noticed until you disassemble the hotend or use high speed retract. Without the mod start gcode your firmware probably limits Extruder speed and retract to 25mm/s.  Also I have to guess you are printing ABS, probably on an Ender-3 with regular PTFE which is prone to clogging in some situation with high temp

Finally, please keep in mind there is a strong relation between the slicer settings and the machine capabilities / issues. If you need to adjust some settings specificaly for your machine, there is probably something wrong with it. It could be as simple a lack of hotend cooling that makes clogging to appear with aggressive retract. 

I'm closing this bug - again - by lack of proper feedback, complaining isn't enough.

Please try my suggestions and report another issue with all the details of your configuration, materials, machine if you want it to be taken into consideration.
