### ISSUE TITLE
CR-X not supported?

### ISSUE THREAD

**Issue by TheMrCaveman** [trouch/CreawsomeMod#8]
CR-X not supported?

Are you willing to add Creality CR-X?

**Comment by trouch** [comment]
To be honest, I haven't played with multi material yet. This is not a priority.
You can use CR-10S profile for single material.

**Comment by lorak41** [comment]
Can't wait for github to allow sponsor anyone. I would definitely support your project. :) Hoping that you could add CR-X one day. Cheers

**Comment by trouch** [comment]
@lorak41 ask Creality to send me a CR-X :-D

**Comment by lorak41** [comment]
I upgraded my CR-10s to CR-X for $20. (driver + stepper motor + V-adapter)

**Comment by trouch** [comment]
The issue is tinkering time, not the cost. I have a MM capable printer in project, but too many things ongoing :-)

**Comment by AtlantaRusty** [comment]
Having the CR-X MM capability would be phenomenal in this mod, but using it as a single feed 10S for now is great.  Thank you for the mod.  Looking forward to getting better prints from my X, and hoping you can find the time in the future to add the X to the lineup.

Awesome job!

**Comment by Beeez** [comment]
I second this!

**Comment by trouch** [comment]
Please submit FR or PR to Ultimaker Cura repo
