### ISSUE TITLE
Won't work on Mac OSX 10.14.5

### ISSUE THREAD

**Issue by FilamentFriday** [trouch/CreawsomeMod#80]
When I install it on Cura 4.0 or 4.1 I follow the instructions for replacing the Resources folder but it breaks Cura. Get the attached message and won't let Cura start.
<img width="436" alt="Screen Shot 2019-06-11 at 1 42 56 PM" src="https://user-images.githubusercontent.com/51718497/59295730-661e9d00-8c52-11e9-9f6f-961a206c9970.png">

**Comment by Projectile007** [comment]
The folder structure under Cura 4.1 is different. Under the Contents/Resource folder there is another folder with a lower case "r" (resource) just replace this folder with the resource folder in Creawsome! you are good to go.

**Comment by FilamentFriday** [comment]
Doh! My mistake. Thanks.
