### ISSUE TITLE
Custom Machine Multi Material support

### ISSUE THREAD

**Issue by prepajar** [trouch/CreawsomeMod#81]
Bonjour,
Tous d’abord bravo pour ce travail !! j'ai test sur une ender 3 et c'est parfait !!!
En revanche, je voulais tester sur une Anet A8-m à doubles extruder et je constate qu'il n'y a pas la possibilité de configurer en "custome machine" avec double extruder. J'ai pensé que c’était un oubli pour la version 4.1 de CURA mais même problème sur 4.0 CURA. Avez-vous en projet de rajouter ce manque ?  
     Hello,
First of all congratulations for this work !! I test on an ender 3 and it's perfect!
On the other hand, I wanted to test on an Anet A8-m to double extrude and I see that there is no possibility to configure in 'custome machine' with double extrude. I thought it was an oversight for version 4.1 of CURA but same problem on 4.0 CURA. Do you plan to add this lack?
Merci

**Comment by trouch** [comment]
Yeah, but I need to play with dual and multi material first !
That's a low priority for now.

**Comment by trouch** [comment]
Et merci ;-)

**Comment by trouch** [comment]
https://github.com/trouch/CreawsomeMod/issues/8
