### ISSUE TITLE
Cura 4.1 Crash

### ISSUE THREAD

**Issue by nvladik** [trouch/CreawsomeMod#83]
Crash on a brand new installation of cura (so no settings to clean up). I installed Cura 4.1, backed up Resources folder, copied over the new folder, as soon as Cura tries to start there's a crash "application quit unexpectedly" with nothing useful in the crash report.

**Comment by infrat** [comment]
Are you sure you'd replaced correct resources folder? Keep in mind, that there are two 'Resources' folders inside Cura package. One is on the highest level (started with BIG letter), and the second one inside (started with small letter). You need to replace that second one.
<img width="515" alt="Screen Shot 2019-06-16 at 13 42 28" src="https://user-images.githubusercontent.com/6294912/59563659-10286b80-903d-11e9-9529-bec3767c4c77.png">
 It might be little bit confusing (so my advice for Author is to update Readme with that note)

**Comment by trouch** [comment]
most of crashes are caused either by 
- wrong zip file downloaded, you have to download it from the releases tab
- wrong `resources` folder replaced, need to replace the lower `r` one
- user setting corruption upon existing profil import, which a settings reset solves
