### ISSUE TITLE
Poor top layers

### ISSUE THREAD

**Issue by Luksusfinger** [trouch/CreawsomeMod#84]
Probably me that do something wrong :P 
But i have tried, different fan speed (i have two 5015 on my ender 3) i have also tried with out any fan speed, i have tried tilting the figure, but it appears on the same height. I have linked some photos, to visualize my problem (i am kinda new to 3d printing)

Also the side and first layer seems fine :)

![64344573_353331575328183_3467850796308103168_n](https://user-images.githubusercontent.com/51926915/59626847-359c9e80-913d-11e9-8797-9009fa4e72e6.jpg)
![64409394_437677247025737_5869141215928123392_n](https://user-images.githubusercontent.com/51926915/59626851-36353500-913d-11e9-8b2d-9b851a9c9c8e.jpg)
![64537414_638569089988270_950375433952559104_n](https://user-images.githubusercontent.com/51926915/59626854-36353500-913d-11e9-9ed5-889fad478776.jpg)
![64652517_1053207255069595_6847712818121146368_n](https://user-images.githubusercontent.com/51926915/59626855-36353500-913d-11e9-8b6c-1840d423dfd6.jpg)

**Comment by trouch** [comment]
That's a not seen issue before.
If you started straight with the mod, it's hard to say what you are missing, could be anything but definitely not related to the mod IMO.
