### ISSUE TITLE
Instructions for running Cura from source

### ISSUE THREAD

**Issue by plasticlobster** [trouch/CreawsomeMod#87]
I currently run Cura from source using instructions located here:
https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-macOS

I noticed this mod seems to assume you're running a packaged application. Any chance you'd have a procedure in place for running this mod from a source install where the in-point on Cura is through running `python cura_app.py`?

Cura has not historically been quick to release binaries for their software, particularly for MacOS.

**Comment by trouch** [comment]
There is a PR to include the mod into Cura. You can get the source code from there and eventually merge in your own repo. 

https://github.com/Ultimaker/Cura/pull/5809
