### ISSUE TITLE
CreawsomeMod-4.1.0 Z Seam Alignment - Sharpest Corner don't work

### ISSUE THREAD

**Issue by juckendesAuge** [trouch/CreawsomeMod#88]
Hello,
Cura doesn't always start at a corner with CreawsomeMod-4.1.0 (CreawsomeMod-4.1.0.mod20190530-0.3.2-x86_64.AppImage i use the Linux AppImage).
I am currently printing https://www.thingiverse.com/thing:73489
penholder.stl
04-14-13
82927 29mb

Starting point 1 is ok.
But at 2 it starts in a curve.

![sharpest_corner](https://user-images.githubusercontent.com/24550429/60382599-b6c13300-9a65-11e9-86b9-6e4f6a5ac521.JPG)

Settings:
Dynamic Quality - 0.16mm
Z Seam Alignment - Sharpest Corner
Infill 15% - Gyroid
Printing Temperature - 220°C
Build Plate Temperature - 55°C
Build Plate Adhesion - Brim

Many greetings

**Comment by mkh97** [comment]
<img width="960" alt="tuning-zseam1" src="https://user-images.githubusercontent.com/51927104/61205173-07888b00-a6f8-11e9-9dbf-84ee1e526a16.png">
Try This

**Comment by juckendesAuge** [comment]
I have test user Specified.
The seam is then in the middle of the printed object.

![schwein](https://user-images.githubusercontent.com/24550429/61237978-ff523f00-a73b-11e9-9ec7-17a76c8a56ee.jpg)

Or is Z seam y 90 decisive?

Thank you very much for help

**Comment by mkh97** [comment]
I think try both a minimal same parts and give your decision but my idea is y 90

**Comment by juckendesAuge** [comment]
Thank you very much.

**Comment by trouch** [comment]
The Y=90 is just an example to show how you can move to a corner

Seam corner preference is only effective when there is a corner on the layer. Totally curved parts don't have any corner.

With regards to the pig, the seam splits in two where you can't have a single perimeter. The ears are basically two separated circles at this point.

Cura just tries to place the seam as close as possible to the X/Y positions configured and to fulfill corner preference. Hence I set it to "None" to only use X/Y positions.
