### ISSUE TITLE
Is there a way to support Linux?

### ISSUE THREAD

**Issue by mhcerri** [trouch/CreawsomeMod#9]
Hi,

Awesome project! Do you think is there a way to support Linux as well? I believe Cura is shipped for Linux as a single AppImage file, so that probably make things harder.

Are you planning to release it as a regular Cura plugin maybe?

Thanks.

**Comment by trouch** [comment]
I hadn't time to look into Linux version yet. ASAP :-)

**Comment by fdraeger** [comment]
Hi there, 

I managed to install it on Linux (Linux Mint, but should work on Ubuntu and Debian derivates, too).
With Cura 4 installed, go to ~/.local/share/cura
Rename the folder 4.0 to 4.0_old
create a new folder 4.0 
change into this folder
extract all the files from the CreawsomeMod download into this folder.
you may remove the __MAXOSX folder

Starting Cura, you should now see a new startup splash window.

Cura seems to be very sensitive with extensions installed on top of CreawsomeMod. It complains about inconsistent config files and wants to reset to factory settings. If you do this, you loose the whole CreawsomeMod settings. - profile and all.

Cheers,

   Frank

**Comment by mhcerri** [comment]
Thanks! I will give it a try

**Comment by ltgrbrnz** [comment]
I tried Fdraeger's instructions.  Didn't work.  But.  I recreated my original 4.0 folder and simply copied the contents of the resource folder into the 4.0 folder, merging where requested, and it worked.  (At least so far. Printing test cube now.)  btw, I'm running Mint also.  Still copy the 4.0 directory to 4.0_old if you try this!  I'd hate to be responsible for any loss. Thanks Frank for the pointers.

**Comment by probonopd** [comment]
Would you be interested in having an AppImage? I think I could help.

**Comment by drewlio** [comment]
I just did this and it seemed to work. Slight modification to @fdraeger 's earlier instructions. 

Save any custom materials or profiles before doing this.

`rm -rf ~/.cache/cura/4.0`
`mv ~/.local/share/cura/4.0 ~/.local/share/cura/4.0-old`
`mkdir ~/.local/share/cura/4.0` 
`mv /path/to/unzipped/CreawsomeMod/resources/* ~/.local/share/cura/4.0`

Start the appimage, new splash screen, pick the CreawsomeMod Ender3...bobs your uncle.

This is Mint 19, Cura 4.0, Creawsomemod 0.2

**Comment by probonopd** [comment]
A CreawsomeMod AppImage build is available at 

https://github.com/probonopd/CreawsomeMod.AppImage/releases/tag/continuous

__CAUTION:__ So far completely untested. I expect that some fine-tuning will still be necessary. I don't know if it can mess up your normal Cura's settings. If you fear that, please make a __backup__ of your `~/.local/share/cura/4.0` before you run this.

**Comment by trouch** [comment]
Thanks for pointing that out !

**Comment by probonopd** [comment]
0.3.0 uploaded.

**Comment by rdehuyss** [comment]
Will there be an CreawsomeMod Cura appimage based on Cura 4.1?

**Comment by probonopd** [comment]
Sure, if I get feedback from users whether it works as intended.

**Comment by ltgrbrnz** [comment]
<sarcasm> Well, you'll get feedback if it doesn't work!

**Comment by ltgrbrnz** [comment]
Hmm that had a Sarcasm tag that actually disappeared. It was meant to let you know that somebody is listening.

**Comment by rdehuyss** [comment]
Working for me! Still need to learn a lot about Cura as I'm an absolute
beginner. But I did finish my first successful build.

**Comment by deepfriedcode** [comment]
Works well for me, thanks @probonopd.

**Comment by probonopd** [comment]
New builds have been added to https://github.com/probonopd/CreawsomeMod.AppImage/releases, including 4.1.

**Comment by mhcerri** [comment]
Awesome work, @probonopd ! Thank you!

**Comment by gleonard3** [comment]
@probonopd, I use this on my Chromebook.  Works great.  Thanks for doing that.  I hope you stay on top of it.
