### ISSUE TITLE
Z Offset Ignored on CR-20 Pro

### ISSUE THREAD

**Issue by rjnich** [trouch/CreawsomeMod#91]
I am using the basic CR-20 Pro profile from the resources folder.  When printing, I receive a transparent first layer after the initial Cura purge line results without an issue.  Actual extrusion is only noticeable on following layers.  Z-Offset on the machine is set to -3.00 and prior to using the mod did not have an issue.   After testing different offsets, I have noticed no changes while using the profile or any modification of the starting gcode.
![20190715_172013](https://user-images.githubusercontent.com/32175641/61253002-27827380-a725-11e9-984f-37f193182c7a.jpg)

**Comment by trouch** [comment]
change the M420 with a G29 within the start gcode and report

**Comment by rjnich** [comment]
That seems to have fixed the issue, thank you for the assistance.

**Comment by unimonkey1994** [comment]
Ok.  So I tried this but it didn't work as expected.  what is it just "G29 Z0" or something else at that line?
