### ISSUE TITLE
Cura won't launch

### ISSUE THREAD

**Issue by ReauLeau** [trouch/CreawsomeMod#93]
Hi!

I'm using Cura 4.1 and I've downloaded the creawsomeMod for the same version. I renamed the 'resources' folder to 'resources_backup' and placed the extracted 'resources' folder from your mod right next to it.

However, when I try to launch Cura, it won't start. It look like it's loading but nothing is happening.

**Comment by ReauLeau** [comment]
I'm on windows by the way

**Comment by ReauLeau** [comment]
Nevermind. It worked after restarting my computer.

**Comment by tvixen** [comment]
You should close this "issue"

**Comment by ReauLeau** [comment]
OH yeah, you are right! My bad :)
