### ISSUE TITLE
Model print order placement request

### ISSUE THREAD

**Issue by LD3D** [trouch/CreawsomeMod#94]
In Cura when you place multi models on the build area and select to print one at a time there is no setting to set the order it prints each model. or if it prints from front models to back models.

This is an issue if printing tall parts on a gantry style machine. to fix this having placement and print the first number for each model would solve so many issues.

Solution if you select the model form a group right-click and select the print order. this changes depending on how many models are on the build bed but having a print order will greatly improve being able to print multi models of different heights and the order on the build bed.

Please consider this because it is a huge downside right now.

Thank you.
Cory S.

**Comment by nallath** [comment]
That has little to nothing to do with this mod, but with Cura itself. See https://github.com/Ultimaker/Cura/issues/4835 for the discussion about this.
